// <auto-generated />
using Microservices.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservices.Services.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservices.Services.CouponAPI.Controllers.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAccount")
                        .HasColumnType("int");

                    b.HasKey("CouponID");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponID = 1,
                            CouponCode = "20REDOFF",
                            DiscountAmount = 20.0,
                            MinAccount = 40
                        },
                        new
                        {
                            CouponID = 2,
                            CouponCode = "40REDOFF",
                            DiscountAmount = 40.0,
                            MinAccount = 80
                        },
                        new
                        {
                            CouponID = 3,
                            CouponCode = "60REDOFF",
                            DiscountAmount = 60.0,
                            MinAccount = 120
                        },
                        new
                        {
                            CouponID = 4,
                            CouponCode = "80REDOFF",
                            DiscountAmount = 80.0,
                            MinAccount = 160
                        },
                        new
                        {
                            CouponID = 5,
                            CouponCode = "50REDOFF",
                            DiscountAmount = 50.0,
                            MinAccount = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
